[tool.poetry]
name = "feedparser"
version = "6.0.2"
description = "Parse Atom/RSS/JSON feeds in Python"
readme = "README.rst"

repository = "https://github.com/kurtmckee/feedparser/"
documentation = "https://feedparser.readthedocs.io/en/latest/"

authors = ["Kurt McKee <contactme@kurtmckee.org>"]
license = "BSD-2-Clause"

keywords = ["atom", "feed", "json", "rdf", "rss"]
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Topic :: Text Processing :: Markup",
]

[tool.poetry.dependencies]
python = ">=3.6, <=3.9"
sgmllib3k = "^1.0.0"

[tool.poetry.dev-dependencies]
tox = "^3.20.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
